### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by hefnetefne** [ascott18/LibDogTag-Stats-3.0#1]
VTMW Version 9.0.8 TBC

Steps to repro:
- Create a new icon of any kind.
- In a Text Displays field, enter `[SpellCrit]`
![image](https://user-images.githubusercontent.com/1365705/129416384-855e4414-f276-4c58-abd9-27933f80ce23.png)

Result:
I expect it to show me my crit percentage on the icon.
Instead, I get a lua error and no text is shown on the icon.
![image](https://user-images.githubusercontent.com/1365705/129416231-1cb9969c-bf84-4048-9597-274c806223e4.png)

**Comment by ascott18** [comment]
Its game-version specific - `GetSpellCritChance` works OK on retail.

**Comment by ascott18** [comment]
Fixed in b1822728ec2a541091bd3598b553ff806774dc70
